### ISSUE TITLE
如何设置密码捏

### ISSUE THREAD

**Issue by billowssun** [chrysoljq/pandora-vercel#1]

**Comment by chrysoljq** [comment]
你说的是无需登录直接使用？

**Comment by billowssun** [comment]
不是 我的意思是密码保护 不过每台设备都重新登陆openai账号 就不用了

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: chrysoljq ***@***.***>
发送时间: Wednesday, April 26, 2023 7:29:36 PM
收件人: chrysoljq/pandora-vercel ***@***.***>
抄送: billows ***@***.***>; Author ***@***.***>
主题: Re: [chrysoljq/pandora-vercel] 如何设置密码捏 (Issue #1)


你说的是无需登录直接使用？

―

**Comment by chrysoljq** [comment]
自己搭建都是安全的
