### ISSUE TITLE
这是啥情况，请问下大神，谢谢

### ISSUE THREAD

**Issue by kxkxpack** [chrysoljq/pandora-vercel#10]
Explain quantum computing in simple terms
ChatGPT
!
An error occurred. Either the engine you requested does not exist or there was another issue processing your request. If this issue persists please contact us through our help center at help.openai.com.

**Comment by chrysoljq** [comment]
有更详细的信息吗？部署到哪的？包括浏览器控制台截图

**Comment by mmwong1984** [comment]
我也試過，但是改密碼後就可以啦

**Comment by kxkxpack** [comment]
[](https://img1.imgtp.com/2023/05/17/3SVix1c4.jpgl) 这样，我改密码之类的也没效，不知道咋回事

**Comment by kxkxpack** [comment]
![QQ图片20230517192158](https://github.com/chrysoljq/pandora-vercel/assets/131777219/66b436ca-d3b5-4f04-b470-0e17063e602c)

**Comment by chrysoljq** [comment]
> ![QQ图片20230517192158](https://user-images.githubusercontent.com/131777219/238970775-66b436ca-d3b5-4f04-b470-0e17063e602c.jpg)

部署环境呢？以及浏览器控制台截图呢？

**Comment by kxkxpack** [comment]
vercel部署的，我看看，好像是被限制了 
![2023-05-17_21-53-05](https://github.com/chrysoljq/pandora-vercel/assets/131777219/05a27cb2-9180-4a12-addf-88ad69571f8a)
![2023-05-17_21-53-22](https://github.com/chrysoljq/pandora-vercel/assets/131777219/4aea8ef9-6a12-418f-9a72-e0747de87a5f)

/

**Comment by chrysoljq** [comment]
不是我的问题，你可以问问 [pengzhile/pandora](https://github.com/pengzhile/pandora)

**Comment by chrysoljq** [comment]
https://github.com/pengzhile/pandora/issues/390
