### ISSUE TITLE
账号登录问题

### ISSUE THREAD

**Issue by gavin1108** [chrysoljq/pandora-vercel#11]
请教下，openAI开启了双重验证，使用用户名密码登录会提示callback failed之类的错误。不开双重验证能正常登录。有没有解决办法呢

**Comment by chrysoljq** [comment]
https://github.com/pengzhile/pandora/issues/454

**Comment by gitMFQ** [comment]
> https://github.com/pengzhile/pandora/issues/454

是还没有同步过来吗

**Comment by chrysoljq** [comment]
> > [pengzhile/pandora#454](https://github.com/pengzhile/pandora/issues/454)
> 
> 是还没有同步过来吗

pandora-cloud也没有同步双重登录，在加上我现在没什么时间

**Comment by chrysoljq** [comment]
支持了，不过实现的不太优雅 https://github.com/chrysoljq/pandora-vercel/commit/4920646ad4f05a18d5b938380bdfd61a5120b4ce
