### ISSUE TITLE
想问一下直接请求https://ai.fakeopen.com的方式是什么，如何添加access_token?

### ISSUE THREAD

**Issue by 14790897** [chrysoljq/pandora-vercel#14]

**Comment by 14790897** [comment]
我以为可以直接通过fakeopen获得chatgpt回答，而不需要使用pandora，大佬的意思是自己搭建的pandora也是通过fakeopen请求的吗？

**Comment by chrysoljq** [comment]
> 我以为可以直接通过fakeopen获得chatgpt回答，而不需要使用pandora，大佬的意思是自己搭建的pandora也是通过fakeopen请求的吗？

是的，fakeopen是pandora的一部分。pandora-cloud 为fakeopen 提供了一个类官方 UI。

**Comment by 14790897** [comment]
好的
