### ISSUE TITLE
自定义域名好像 https 自动配置失败了

### ISSUE THREAD

**Issue by fatfoo** [chrysoljq/pandora-vercel#16]
如题，你有了解吗？

https://chatnow.uprogrammer.cn

**Comment by chrysoljq** [comment]
你是不是环境变量 chatgpt_api_prefix 设的 `chatnow.uprogrammer.cn` 而不是 `https://chatnow.uprogrammer.cn`？

**Comment by fatfoo** [comment]
非常感谢，早上起来 https 生效了，可能是自定义域名的 https 需要耗点时间。

另外 chatgpt_api_prefix 没有带 https 确实会导致后面的 API 调用失败。

**Comment by limkz27** [comment]
你好想要请教一下
