### ISSUE TITLE
能部署到Zeabur吗

### ISSUE THREAD

**Issue by billowssun** [chrysoljq/pandora-vercel#2]

**Comment by billowssun** [comment]
我尝试了一下 不行 > 按照文档，现在应该可以部署到 Zeabur 了，我没有具体尝试，你可以试试看

**Comment by chrysoljq** [comment]
没有问题的 [https://pandora-zb.zeabur.app](https://pandora-zb.zeabur.app)

**Comment by billowssun** [comment]
![image](https://user-images.githubusercontent.com/55521033/234736081-ec769729-ea1b-49a3-9084-6ade47f5b776.png)
为啥我部署完显示这个，是哪里需要特别设置吗？

**Comment by chrysoljq** [comment]
我部署时没有额外的设置，不过你可以尝试在 Variable 中添加环境变量 PORT=5000，此外你要确保你部署的是最新更改后的仓库
![image](https://user-images.githubusercontent.com/58966022/234747167-98865ccc-d21f-4035-8e9a-4cf2d12d627e.png)

**Comment by billowssun** [comment]
谢谢，同步一下仓库后就可以了。
