### ISSUE TITLE
在vercel部署了后无法连接服务器

### ISSUE THREAD

**Issue by limkz27** [chrysoljq/pandora-vercel#23]
![image](https://github.com/chrysoljq/pandora-vercel/assets/64255582/8037edd3-4f6a-4c7b-b05c-c0f806089233)
![image](https://github.com/chrysoljq/pandora-vercel/assets/64255582/f54d09a7-98b2-456b-a008-cc4e3bffff3b)

**Comment by TiMi518** [comment]
我也这样，应该是反代问题，在哪里修改呀

**Comment by chrysoljq** [comment]
https://github.com/pengzhile/pandora/issues/628
