### ISSUE TITLE
登录界面恢复

### ISSUE THREAD

**Issue by yinm0591** [chrysoljq/pandora-vercel#8]
docker部署 https://github.com/pengzhile/pandora 最新版，登录界面(用户名/密码)能正常工作了。能否把登录界面恢复出来？或者有1个环境变量指定是否要出现登录界面？

**Comment by chrysoljq** [comment]
好了，现在可以添加环境变量 `LOGIN_LOCAL=1` 恢复登录界面，不过得注意可能有限频

**Comment by yinm0591** [comment]
可以用了。太感谢了
