### ISSUE TITLE
聊天介面建议

### ISSUE THREAD

**Issue by mmwong1984** [chrysoljq/pandora-vercel#9]
期望聊天界面可以给用户选择现在的那个版本和官方的那个版本，期望很多地方都可以自定义，这样会比较好

**Comment by Nothingness-Void** [comment]
> 期望聊天界面可以给用户选择现在的那个版本和官方的那个版本，期望很多地方都可以自定义，这样会比较好

理论来说 你可以自己修改html文件去改聊天界面 大概

**Comment by yanjiecao** [comment]
你这个意见应该是去pandora那边提。
